name: PR Check

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ===== SETUPS ======

      - name: Setup codebase
        uses: actions/checkout@v4


      # ===== JAVA ======


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 19

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      # ===== BUILD ======


      - name: Execute Gradle build
        run: gradle build

